// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H35cts4mviroDhTFbuHlHXb1q+mfuW2lY6m42N8ZGc78nog8pOEhATYAGhHnfK/+wD7iPskWzh4irJk",
	"x06mp/OfTOL47gsf6M+Oz6KYUaBSOIPPTow5jkAC138dYolDNhtJiEbBGZZz9TAA4XMSS8KoM3CuKPk1",
	"AUQCoJJMCXA0ZRzJOSDfTEZEQuS4DnzCURyCM3BEhMPQu1UPiVoiVgu7DsWReusX93Rch8OvCeEQOAPJ",
	"E3Ad4c8hwgZWKYGrFf7rPfZ+a3r711v2h3f9uen2W/fp8+3//2fHdeQi1vtLTujMub93SwhSITH14csQ",
	"RcQu80SMMyBeGvML4LfEh8tF/ASMhZmM9LJFRFehKIq7vSxq92p1ETMqQMvwQcgBB4vhJyKMiPuMSqBS",
	"/cRxHBIfK3x3PgiF9OccGUUOiUnoDIrEQndEzhEJ0KvbyFPMCjAPXiFsdkFgtlFEsHIwcJp+f3c278+9",
	"Xdjve7s9HzzozPc8aM36e535tLu/p0glJJaJcAbd5r7rSCI1Qc9BsIT7sLyBxfvg7fnw4Og/b4b/GF1c",
	"Xjj3RVr+mcPUGTh/2sl1fMe8FTtDzhk35Cpz3dILWYLdu86PODiHXxMQ8onke00gDNArKwQ3CvJXKEqE",
	"RJRJNAEEUSwXZaLt7ne6wbQDXnfS73jd9v7EmzSnPW+yF3R6TfBb/R6UiNbMiTaitzgkAeIGalQwahnd",
	"RifvDt6Ojm4Ozn+6Oh6eXD4D5X7EAUoJde86rxmfkCAA+kSqXQngKGAgNJXm+BZQDDwiQhBGkWQI+z4I",
	"geScCMStnJSJuIe7PZh2p17P3+16vQ72Pb817Xv+PnT7rWnQ3u1PS0Ts5EQ8MKtPMywy0p0Nz49HFxej",
	"05Obo+HJaHj0DLTLiXXvOm+wSA3hUzW2YNgrmjrHIjPSL6Go1fUt0V4fjN4Oj27OzoeHpydHo8vR6ckz",
	"kO0NFign1b3rjKiynjhUFgu4mfc0Ch5QlFD4FIMvIUCgVkLM9xPOIUB3cxICijlTMkLoTHsFq25lmrZh",
	"b5982Pvg7c9ae97+Lsy8We9D05t1yF6z92HebzU/FGjaK+uxQUb7G+AGiKIKXw7PTw7ePgMds50M3ZAd",
	"6DonTL5mCQ2ewXGUxTBTbG3QyzTbn/T601lv5vWDvZ7X704CL2jPdr2gOe3ttmfQ2dudleSwWyOHau2p",
	"Bj0j2Mnp5c3r06uT51DYEyaRocy965yxkPiLI4iBBkD9xROpZZZBcIvDRI9GIvF9gAACNEkkwiiNG1CQ",
	"7YXusCGkwJKIKYGgTMyO3+0F0J96u7O9fa/ZmhPvQ7vT9T72wv7uXkT3my1WJGa7QEwLUL7ZS+uz3bBA",
	"yYy65/BBq+ITaWsdE+J2GTRZILvbkM4IrXiOFm53Jn438HrQ3/X29qczb95stT3S+dDt9T+Gu3v7UUkE",
	"+0tUS3f6SjTL6KMoxtktCb7M/l2cnR8rC6cXykxP0bJNOl0/6IHXn+7uefvN2dwjrXbH+9D92OvvhtHe",
	"fpOWBKtdIFF13ZelULpbZtauKE7knHHy25MF6p0OsdQyKj0wE5DPQWcLOBQIc8j1daNwpe+3OwG0A6+D",
	"e22v297DHu43ex7eDdrdZjBp9rpBSehahXClDEiWYGSkvTo5uLp8Mzy5HB0eXD5LzFIi4n22XjVz1lkN",
	"ZzFwSUw8g2NycwtcEEPd8qrvzAvEptqpFgMZsz4iUkA4RVvQmDVcdNvCYTzHre3GmI6iKJF4EgLCUwlc",
	"sUOTozGm5TTNznHcYr51+15lVX9R6dX1X8zvmgTLdfSqcCNJBMvgX5IIhMRRjO7mQJfzY2WtzQIB2jp/",
	"fYg6nc7+dgm6drPd95otr9W5bHUH7eag2fzFcZ0p4xGWzsAJsARP765SPRyc0nCRJpJLwAZExCFe3JhE",
	"dCnFFcC9KSdAg3CB7FikxtZm940xPU4JTIPch1MwIj4BlOikuUrwiwiHITqCWwhZHAGV6N2x4zoR/vQW",
	"6Ewl3/2O60SEpn+2alCJa7P0zOGr14gYkhtaDVLgPQW82Plcqq3cV2Asjy2ULAoiUh6zWYK+lkUiBn+d",
	"EhbU4EINv3edhARPrdI00KWyQlOdlxKBWCLjRHqMhgvF2DElqxQJXc4BjY6Qj6niNtP74jBcIIWF2jFA",
	"twSP6a8J8EWeeSJjHPUi/w+RqRYb610CNyuqAEczoMCxBIEwuroaHTXGdExfszBkdwIdDM+8Vrud2U8N",
	"CqO3CltGRVXs+r0m7HWbTQ9U/txtBV0P77b6Xrfb7/d63W6z2WytE8NHF2TW8juJgy+zHyEWEkUsMOTe",
	"wIr0Bq0vsSL32RM2UUGG4zqfPAyxl7mxvHAlnMF7p17tbtSfNyS4d65dJw4TjsOq2invRugsCTGvvMoN",
	"cfo0whTPgDcCP2oQtlMavKK2+WyuKF3wu0v61i4pqzX8rn2Tl1VMyk4qK4c/5KwKk9d7rcLgb+O+Upye",
	"wY3lvP/uz777s0f5s/wA5n3JB1Ssk5Xu6y9xgDW6bT2hff6gS/SKtdQVvtErHLpt7iTzWSu85VtiTjzK",
	"HpPCJ3kT4xncSPYRarzmpXqs9ZWD5ARu0/qomonUzMaYDqNYLpBhCCI0UHkr2OSYCD1cS4UdXpIEWPzt",
	"9pfol99++cffyemHq7vp3//61zqnyEEkoTnzqhzxcI4XyqvXGpNMGXV1XEclj7duTh4zYbXbktClwLlL",
	"BF0StnruXFizW0btwlgtWwVQTMD1WLoogCmhKW9KYzhMgQP1YUyVKzVm1Wd0SmYJxwXLVJaMSphXIxl5",
	"EGU2Gh0Zjq/igwVDPCaOUr5vjbNOGXxDAvEY35NZaevJz0Lsg44Yjq2ajemDjggJkGiyKLqHINEqUEYn",
	"k7pHmf72EuZrTfeKAVZkXScRwG9ucZjAQ2qkRiEzytJqFU8r6D2kVCoOfKfWXKtKVbkrg71Gnf5gRu5L",
	"bNvL2bSn2bIGGt6qoKyEYAB+iDmIMWUUEOMoYhx0+hDkyKOtf2a//+miiFDU2m6gA6QcbAiZWx9TNp2C",
	"Zl8iQKDCLNMHofYAKvmizh7mtF5C7aQMTwMNsT83K2UYIFzqM3Gz4HRMC6c/jAcaQBc9bKofw+w0bVFc",
	"iggdmamt9dy36D7A7fNCwFSR1wqTNIEJrfK8hs4a6Yc0oI4quaFKN1QKq7hQGme8JAj1VEiOCZXC5Jcw",
	"xUrY9ToGgjG1fqHItjSP8OvM+0O80E0jh0VYlvUv7S/a1IUVsE3JW3X+Y2qLGFqwxNHERTiOt6vmKX27",
	"ibPVIiJu1qiDUJxicq58u4Un11c5x9J0zHBQPDrXLTpCYgljOoGp0vEyekSYdExF9RBUwH+fw39dYMca",
	"TKq0L/bz1Ac7F0VBqBO4B6KardvIVVInMaHAXRRgiSdYgIv8MBFSPRKScTyD7cfHQBXVTXOdIkJ1Spyd",
	"J5ZR1Y9R2nWGpjq5VUZTZXK7e81ddMbZJIQIHenTM6M0by4vz9DB2UiYKFOnwvsdc0aHztMWtjr9Kat/",
	"eiJXhepNEmHqqQhHExg+xSGm9ljdrokkMyyxjR0q6rTFPn0w2RjTY7xIuZA2eHjZ9MCiIxmaQxijACaJ",
	"CQOIEMuVpo37wJZEjxQKmBuregZmqXnFRGGHpt6RCAjMBI79j4plxrZNktmM0FkVgQ2b0rKcPOHEy6L4",
	"OrzSo8wl3inZMC+RzwJAWxGW/hxEGocbSTMjSnUC3QiXAUCo7LTzjQmVMAN9AmzPTZdijjnj0kXzsuyI",
	"JIowX5RkQyt1Y0wv5iwJA0VM5SKIkCofwD5noihWIp0rcFRZoEThTVr3qhapisMx9ueEQkH09XaKjg10",
	"pXTqYKipq1txCm/TehNNImUVlloE3aVDZLfQU+NWezHdmk451zkfXpxenR8Ob4b/eHNwdWFWqTv3d52D",
	"H0/PzfvTq8ub09c35wcnPw01GKPjs7dDBZR+nXVCaQjfHYzeHvz4Vg08Gh4cvR2dqM0Oh8Oj4ZEyawVq",
	"L2O4qexWLKjtBLbynIpXnQ2t8etL6YcNLpZZe2RemGQr13Qdf6jkU/kZExwKxGy5Wb17JdKTii1b6TR4",
	"uIgm0UT5kgljIWDqIgOpi7Sb0ycYUwQB0V7qr1McKg9UzGCm5BMEBqDKYJ1SlsYSSiTB4Y5IZjMQsjCv",
	"qARt16FJGKo1TF6qOw80UjeGWo+Lm0w3kTilmx4+YF9ZwhBPIKzQWGX+V6Odw7cjgyuLiJQQuEgF4bfK",
	"lnIWaVR1xd+GUmPn1o+Ths8SKscO+t///h80dt75cYIOzaMlD354dmXeLVdzl4xASu+S4BhGVbD7jzno",
	"+ApooHN2ocveuvC6KCJppEvXa60dUvSwbksYzDNJgLzaYURB+1RIA+RaDpeKDVbyVp+iHDHpUSaN69Z0",
	"lQzhnCFrQ+5hYzaoMEExJYKI8UVDkN/gZjZJn0msIq2G5r5oSAJ87FTjq2yh9eGvNucakJu83QYHATG5",
	"3FlB7w1Vyrj/7eL0BF0Y1S2mIEos06V15SFj3lbA8VSidrPd9FptJVmnuvpk2pqUO9CMLWmpcmNJHDMu",
	"Re4Xilt/hMUd44EY2FQ0IpRESeSiCH/SP8bUlr9dpNyHHmHIosekP0H6+vzjPDWsAzSXMhaDHd1r5RkS",
	"NRif7Wg0diwaxbdeTtIyX5ayCm3alONV6uQzlVNvtbxWf9tolQLcGbT6mof2D9eJklCSOITTaZGhxcih",
	"bNErjkCL8GZ2P7dLS6AfMppKSKZIKoSLTUZfOO56Jay6Fsw+piaPSt2Ch17rJFVpp0lVBwirGB0CXWET",
	"73++Tk10upsWkkJL98/ZOqnkrF0Kp/m3Bbt2zXMQLFSW0w8JUOkJEgBSeU6gMNGVRQEh+Curznb3QpWy",
	"Xrs+Z3leTSpXDaBiY8gtrEWruGXLeR9hgX7eVpYoxW7JG4+mBfOIpTFd8GuCQ2Gmu4Xxr0S2EOaghpcR",
	"e//zdergiUARjt8bQK7fX2O6GKgFzUzzWLhpQVavpvDUISimC+OV0nFarLSQCuuFliT3EVY5x9ekVbQo",
	"l42HzOjD4ZW9TVXhdZ2aFTrOv6zbo+xRbPBU7u9QvyYgzY9/3WaPvOTzuEaP5qDzZY0eqTNdZoTxrg8p",
	"63LXSAnNn2HhGYWMMeFG+XwsYcY4+c3IpKmHhlKXRxtj+iOTc6smNChqh9WERtWb2PUWzsChIO8Y/1gu",
	"BBU8wIY682A/iBU4T60ldj6Xrgze24Mla1l9TBklPg4fOqWqCl15/cJljLIUloc9V4/Ig6WywxALkVf6",
	"axSwMaaHLIoYTflGqB8mAQzQxlWyxpgeBMrRqxhKMq6M6MKWd5GfCKkCd4UzmsCCUWXBQEBtaW1lC8zm",
	"cZ01U3kpqVx1Tu1NagO3G7kAYIpYjH9VLp9ot4h5VqIqxOkamXx946x18DU02Ag0WZQGD5SHf3c8QMow",
	"u8iExxn9XDRTmcANE65tZVfDD1PSDxCJ9KisaOum96NcZNVHTTiyDBog0NcuXGQNcmGmXtiwb5C/pixQ",
	"AZzClLMQxSFWs9W6wMW2mnNhIB0gH8fYJ3KhsL2caw1PfJlwQLeYE4V5GmAUBE0Lpzml1dRPPcWSXTCE",
	"Ub9s6uAM9nQtS++uxZuIj8IZvFc2xECiR/Wa2YXgCWNFrycC5/5aZQt+nGhB4v6cSNAwOwPn017/pt91",
	"XMd4y0H73pzMFKWsVWOFHtlbVdK47y1Vv6OWqpKLf3Q7VXvQ7b1UO1XJ8j+1nareNeo1l5qnSmPLPVPF",
	"V2tbpUqDK18MeLGmAeX77Cn64/sHTo1X0JsjDwXMaBDmQh+Em/JB4ksUYZoohXy452B4d/ym+cSeg1Lw",
	"nB9zm+OU9KDD6HiKL9IVfo2UNgyPOCotxvzP26OQN6EscfvptaqUHq9EiU5jWq5bodRPb1K7ekRqlfc/",
	"PRCg6n5rLWgmypaYz0CKpx8D36ZUrCRd5UJ23kn0UtXsshFc2cTguGnOaQBfFo57fSw3Zen1QexLU1tY",
	"PgY+OjzO+t5spxg6OBulzk13ethYnPwGAbrDCyU2xiCNaUmZTNeeLRTQoHR2b9IgQqcc5xFPoWxrY0i1",
	"9TT3lmhLPRjSOaa2m02FFUzgUGxncOmlxzQlj8c4ASr1RWRBZlQv/qc/ofM8hFMB2Q8/FFRT/PDDAB2Z",
	"eFtCFIfamCmIAzLV5UBpA3A2XYXEmCK09e54Rcj/czIBTkEtW43+0S0LkwhcbQgLwf62AbPQi6TBPFSB",
	"OASZfqZtQMK0/ZSj6kpniYJRcyYv12qxC4kPVGgdsEHgQYz9OaB2o+m4TsKV90qroXd3dw2sX+tiqJ0r",
	"dt6ODocnF0Ov3Wg25jIKC0eZzgoxUzKc1jzyysO967AYKI6JM3A6jWaja0VeG7edFS3Ig8/ODGSd3dD+",
	"TItyjGeEauqFRMiVbbaiWHTO8nSVk9R3g+owz9FQG0KPAmfgKE9c0xwrNDL5p5zef5ErTr/po/1S/lGf",
	"gu8o3qVdio6Wz2d16dkaKy3tWnml8oUy4RTFwDUMKzaO8CfjuJT5L+2dnf+0ao/B86J3U70vlr2rde5l",
	"sF9rHq1g5hLfNLv0yYPBSVgk7+bAzQlNo9K3ifIj/tTtLJUwKt+RqtBluRF0NVeuK59JajebG1wE3+zG",
	"9Kpe+po71BeJTqWnSZh1NSjV7Bpo6jbJoN4pfJdIT2mtn1K+sq0mddZPKn2bprcJZHVfYdEXxE0fhdXb",
	"FaKky2dM1FiZQ127VDaGwt3KBuOCWVHhhJdnnaMjoTJPreevVl3FeIWqeal2qgFEMZNA/UWdGTKQ1d0D",
	"WGOHTm12XAV1lQ18jDpUNKCSpT7ys2LXJk4CIX9kweIlVSX9hlnxC2n3S9raenkQKsJXy5G0nC4yPQ4X",
	"BQV+FgAf+GpPuVlowoIFSttRkXHmX88ydJv99TMq33LR0/bXTyt/xE7Narc32Kz0GRQ9q7spiOVP0DyT",
	"1TNmYtWVHD1453HXQo2RDEFCXbNQCMZcPnAXo2zHzJSN7FgdLfIhO6u/LFnjers1tr5W3Qyqder2lUR8",
	"A/nJPpn1fHJj2LJabtz1Ubm52bDCr0wWiEixIsT+CeRXF4jmv4Z1n6Z8/DeXr59APqdRGnCYLwKVQeu4",
	"ozaWu+RkNgMuUDrWnvxhar4Ip/KxGt41xvSnQvVfxYHFQr/pXg5hZgqlbOU1vSUpP09B/qPKesazOuv6",
	"SLH8HgqsVblM3jZXvOcov6yuulSO29dVWr5XWL5KhUXUsOa8pqCC6aLmXMEcadu6Sm0rQx3y1SO7b11D",
	"+V47WVM7eVLJZPNKyXPVRJ6lFvJvXQL5hqWPtYHC90pHIUx/SpzykjWEmmCh+rXDx1cKNioQfFFs/OSC",
	"wO+tDrCRxJQ++/7CxYMn1wweUSp4GdFofhPr98etBNhuZr/uH6ToLjVROQ439wzKUpPoj+TrG0XHwGeA",
	"znSzj+5N2+3s97d1NHLCJJir/oUeMp3TZzl+3hKwxYu9KsIt90kIFy1/eGBbt3uTB5v0ywJtMHwJmd4k",
	"jogUqTxN/L+8cEzxbbTKtDl+45jCAJH994Z/fx03Ql0bQZSbJ59WbljVrlR7ydBOJ/qul7IRujCgU36x",
	"qgpR7Cl61ipEY0xPJ7qtqHCRt9ImaENObeJiDreEJSJLP23P4jepZJgLZ/ofQaSZk5t/pUYy1Go2V8P3",
	"VQoeL+nMq9253+sF5XpByTluWi9YocrPXTqwFyVHR4iI1V3/dyQMs9Z/xCisLjoUG4KfWHQYHdVfixjT",
	"40RI2z+Jjk4uvFar3ck/FhBhibZCdgfcxwKQ7rajSQSc+KZ3cL6I50DFduUDAvXXG2gWaG9Qt/s9FDtK",
	"rdpft9ixtHXtjSwj6/+SxY783rv9tyl/tIpH6d8uLscr1TuTG8UvNsctWbp1Oe6D5mVNPrD8fye/lltc",
	"K/R/rBy3Ikz2kmrKRdONvYNjspO3TF/f/18AAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
